// configuration for active model; default view: HadCM3 3xCO2 tas
export let nextMillion = {
  project:          'BRIDGE',
  name:             'emulator',
  experiment:       'nextMillion',
  timeRange:        'kym',
  heightData:       'emulator',
  gridMultiplier:   4.0,
  timeUnit:         ',000',
  timeMin:          0.0,
  timeMax:          1120.0,
  timeStart:        10.0, 
  timeAnimationStart:0.0,
  timeAnimationEnd: 1120.0, 
  timeAnimationSpeed: 22.0, 
  timeAnimationSpeedDelta: 1.0, 
  linearTimestep:   true, // age difference between simulations is variable
  timestep:         1.0,
  showSlider:       false,
  enableWinds:      false,
  enableJetStream:  false,
  enablePrecip:     false,
  enableClouds:     false,
  enableSurface:    true,
  enableLandIce:    false,
  enablePFTS:       false,
  enableVeg:        false,
  enableTAS:        true,
  enableSST:        false,
  enableCurrents:   false,
  staticHeight:     false,
  provideModelList: false,
  modelList:        ''
};
